---
name: 'Build the application'

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [ '1.6.0', 'stable', 'devel' ]
    # permissions:
    #  contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nim Environment ${{ matrix.nim }}
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim }}
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ matrix.nim }}-${{ hashFiles('*.nimble') }}
      if: runner.os != 'Windows'

    - run: nimble install -Y
    - run: nim cli
    - run: nim build
